### ISSUE TITLE
Gracefully exit on KeyboardInterrupt

### ISSUE THREAD

**Issue by emdoyle** [gauge-sh/tach#125]
Right now, if you send a keyboard interrupt (`Ctrl + c`) during Tach's execution, you'll get an ugly stack trace.

Instead, we should catch a KeyboardInterrupt at a high level and exit gracefully (with a nonzero exit code).

**Comment by nikhil5642** [comment]
Hey @emdoyle, the ugly stack trace is due to 2 reason's
1. Impot's taking time to load
2. Tach acutall task execution is not catching keyboard exception.

We can fix the 2nd cause by just adding a simple try catch on main function inside cli.py but inoder to fix this issue completely we will have to go for one hackey solution.

We can fix the first issue by creating a new file let's say(start.py), and call this inside pyproject.toml. So instead of calling tach.cli:main we will call tach.start:start.

This is how this start.py will look like
`from __future__ import annotations

import sys
if __name__ == "__main__":
    try:
        from tach.cli import main
        main()
    except KeyboardInterrupt:
        print("KeyboardInterrupt")
        sys.exit(1)
  `
