### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by R-Peleg** [gauge-sh/tach#167]
I'd like to use this project in my Python 3.7 project. Is it something you consider supporting? What is preventing it

I don't mind to do some work to make it happen if it can be accepted into the project.

**Comment by clin1234** [comment]
Considering that 3.7 is out of support upstream, maybe not. Still looking how to add 3.13 and no-GIL builds for publishing

**Comment by emdoyle** [comment]
> I'd like to use this project in my Python 3.7 project. Is it something you consider supporting? What is preventing it
> 
> I don't mind to do some work to make it happen if it can be accepted into the project.

I looked into this, and we would lose access to a couple nice things. More specifically:
- type hints like `list[str]` cause [pydantic to break](https://github.com/pydantic/pydantic/issues/7873) (since the mitigation we use is 3.8+, [eval-type-backport](https://pypi.org/project/eval-type-backport/))
- `uv` is not supported (could probably get away with just changing CI, but local dev with the Makefile is also impacted)

I don't think it is worth the tradeoff given (like @clin1234 mentioned) Python 3.7 is [no longer supported](https://devguide.python.org/versions/#unsupported-versions).

If you find a way to support the same type hinting syntax, and a low-complexity way to support `uv` in local development when available, this could be accepted, but it doesn't seem trivial. Are you planning to upgrade past 3.7 at some point @R-Peleg ? And is this for a personal project or on a team?

**Comment by R-Peleg** [comment]
This project is a part of a team. We plan to upgrade its Python version, but it will take time due to large codebase and I want to explore the option to add the support here before that.

**Comment by emdoyle** [comment]
With #183, Python 3.7 should be supported. It may take a bit of time before it's ready to merge, and depending on whether it causes more issues down the line we may have to pull support, but we should have a published version of Tach that is compatible with 3.7 soon.
