### ISSUE TITLE
Config `ignore_type_checking_imports` doesn't work with qualified usage of `TYPE_CHECKING`

### ISSUE THREAD

**Issue by edgarrmondragon** [gauge-sh/tach#283]
This works

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
  import ignored
```

but this doesn't

```python
import typing as t

if t.TYPE_CHECKING:
  import ignored
```

We standardize our repos to `import typing as t` and enforce it using Ruff, so it'd be nice if this was compatible with Tach.

**Comment by emdoyle** [comment]
This seems reasonable. Since we aren't using a type-checker/binder under-the-hood it makes the most sense to simply also check for the AST pattern of 'if conditional expression is an attribute access with the name TYPE_CHECKING', since right now it is just checking for a Name node with the exact name match. I'll put up a PR for this.
