### ISSUE TITLE
Add filter options to tach show

### ISSUE THREAD

**Issue by nip3o** [gauge-sh/tach#322]
For large projects with loads of cross-dependencies, the dependency graph generated with `tach show` might be too large and complicated to be readable. It would be useful to filter the graph to only include certain modules in the same way as you can do with `tach report`.

**Comment by emdoyle** [comment]
This makes sense, I think the most straightforward implementation might be an `--include` flag which takes multiple module paths. Accepting filesystem paths like `tach report` might be a bit less intuitive as a user, since the resulting graph wouldn't necessarily have a node that corresponds to the path (if it contains multiple modules defined in `tach.toml` for example). Would that work for you?

```
tach show --web -i tach.core -i tach.errors

-- OR --

tach show --web --include tach.core,tach.errors
```

**Comment by nip3o** [comment]
Yes, I think that makes sense!
