### ISSUE TITLE
SSL error on --web

### ISSUE THREAD

**Issue by larkost** [gauge-sh/tach#427]
On a brand new install (tach 0.14.4) I am getting an error:
```
% tach show fabsqa --web       
Error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1020)>
```
This is on macOS Sonoma 14.7, on Python.org installed Python 3.13.0 version.

**Comment by emdoyle** [comment]
Interesting, this doesn't replicate on my system so I'm guessing a bit. Inspecting the live site, the certificate looks good. From searching around a bit, it seems like this might be because the SSL module within the Python install doesn't trust the certificate authority  (Google Trust Services in this case).

Are you able to visit https://show.gauge.sh in your browser successfully? If so, I think the answers discussed here might help: https://stackoverflow.com/a/62374703
