### ISSUE TITLE
Potential `tach check --strict`?

### ISSUE THREAD

**Issue by jearbear** [gauge-sh/tach#63]
Let me start by saying that I love this! It was super easy to get setup and start seeing value.

I was wondering if y'all have considered adding a "strict" mode that causes `tach check` to fail if it sees dependencies in the `tach.yml` file that aren't actually present. While this might not be part of tach's original vision, it would allow the `tach.yml` file to also represent the current DAG of dependencies in a project. Not sure how often this would happen in practice, but it may be useful to help trim the transient dependencies that existed before adding tach to a CI pipeline.

Thanks!

**Comment by emdoyle** [comment]
Thanks for the feedback!

We definitely want to improve managing your dependencies through the CLI post-init without fiddling with the YML manually. What do you think about a `tach sync` command which (after a confirmation) would essentially re-init the dependencies in your project to match the actual dependencies found in the code?

Would you still want a flag on `check` so that you can enforce a trimmed version of `tach.yml` is always being committed?

**Comment by emdoyle** [comment]
@jearbear Just published `0.1.10` which includes `tach sync` and `tach check --strict`! Let me know if these match your expectations.

A few more QoL improvements are coming soon!
